// Code generated by sqlc. DO NOT EDIT.

package usersdb

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64        `json:"id"`
	Passport  string       `json:"passport"`
	Fullname  string       `json:"fullname"`
	BirthDate time.Time    `json:"birth_date"`
	DeathDate sql.NullTime `json:"death_date"`
}
